name: jra run (predict/result)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "predict or result"
        required: true
        default: "predict"
        type: choice
        options:
          - predict
          - result
      date:
        description: "YYYYMMDD (e.g. 20260201)"
        required: true
        default: "20260201"
  # いったん安全運用で schedule は OFF（必要になったらONでOK）
  # schedule:
  #   - cron: "0 9 * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run (predict)
        if: ${{ inputs.mode == 'predict' }}
        env:
          KAISAI_DATE: ${{ inputs.date }}
          SLEEP_SEC: "0.8"
          DEBUG: "0"
          # ここは必要なら調整（基本はデフォでOK）
          # MAX_FETCH_RACEIDS: "200"
        run: |
          python jra_predict.py

      - name: Run (result)
        if: ${{ inputs.mode == 'result' }}
        env:
          DATE: ${{ inputs.date }}
          SLEEP_SEC: "0.8"
          DEBUG: "0"
          PRED_GLOB: output/jra_predict_${{ inputs.date }}_*.json
          BET_ENABLE: "1"
          BET_UNIT: "100"
          BOX_N: "5"
          FOCUS_ONLY: "1"
          FOCUS_TH: "30"
        run: |
          python jra_result.py

      - name: Commit output (if changed)
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add -A
            git commit -m "update ${{ inputs.mode }} ${{ inputs.date }}"
            git push
          else
            echo "No changes to commit."
          fi
